import '../utils/constants.dart';
import '../models/language.dart';

class AppLocalizations {
  final Language language;

  AppLocalizations(this.language);

  static final Map<Language, Map<String, String>> _localizedValues = {
    Language.hindi: {
      'app_name': 'सहायक',
      'point_here': 'यहाँ दिखाएं',
      'press_to_speak': 'बोलने के लिए नीचे का बटन दबाएं',
      'listening': 'सुन रहा हूँ...',
      'thinking': 'सोच रहा हूँ...',
      'speaking': 'बोल रहा हूँ...',
      'error_occurred': 'कुछ गड़बड़ हुई। दोबारा कोशिश करें।',
      'ask_question': 'कोई सवाल पूछें',
      'welcome_message': 'नमस्ते। मैं सहायक हूँ। अपना सवाल पूछें या कोई चीज़ दिखाएं।',
      'change_language': 'भाषा बदलें',
      'settings': 'सेटिंग्स',
      'text_size': 'अक्षरों का आकार',
      'voice_speed': 'बोलने की गति',
      'normal': 'सामान्य',
      'large': 'बड़ा',
      'extra_large': 'सबसे बड़ा',
      'slow': 'धीरे',
      'fast': 'तेज़',
      'stop_speaking': 'बोलना बंद करें',
      'flip_camera': 'कैमरा बदलें',
      'choose_language': 'अपनी भाषा चुनें',
      'connection_error': 'माफ़ कीजिये, अभी कनेक्शन नहीं है। थोड़ी देर बाद कोशिश करें।',
      'camera_error': 'कैमरा शुरू नहीं हो सका। ऐप दोबारा खोलें।',
      'api_error': 'AI सर्विस में गड़बड़ है। थोड़ी देर बाद कोशिश करें।',
      'permission_error': 'कैमरा और माइक की अनुमति चाहिए।',
      'scan_barcode': 'बारकोड स्कैन',
      'scanning': 'स्कैन हो रहा है...',
      'barcode_found': 'मुझे इस उत्पाद का बारकोड मिल गया।',
      'history_count': 'आपकी {n} बातचीत हैं।',
      'history_play_prompt': 'बीच वाला बटन दबाएं सुनने के लिए।',
      'history_you_asked': 'आपने पूछा:',
      'history_i_said': 'मैंने कहा:',
      'history_older': 'पुरानी बातचीत।',
      'history_newer': 'नई बातचीत।',
      'history_oldest_reached': 'यह आपकी सबसे पुरानी बातचीत है।',
      'history_newest_reached': 'यह आपकी सबसे नई बातचीत है।',
      'history_empty': 'अभी कोई बातचीत नहीं है।',
      'tutorial_next': 'आगे',
      'tutorial_finish': 'खत्म',
      'tutorial_skip': 'छोड़ें',
      'tutorial_welcome_title': 'सहायक में आपका स्वागत है!',
      'tutorial_welcome_desc': 'आइए देखें कि ऐप का उपयोग कैसे करें।',
      'tutorial_mic_title': 'मुझसे बात करें',
      'tutorial_mic_desc': 'सवाल पूछने के लिए इस बटन को दबाकर रखें।',
      'tutorial_camera_title': 'कैमरा बदलें',
      'tutorial_camera_desc': 'सामने और पीछे के कैमरे के बीच स्विच करने के लिए इसका उपयोग करें।',
      'tutorial_flash_title': 'लाइट चालू करें',
      'tutorial_flash_desc': 'अगर अंधेरा है, तो फ्लैश चालू करने के लिए इसका उपयोग करें।',
      'tutorial_orb_title': 'स्थिति लाइट',
      'tutorial_orb_desc': 'यह बताता है कि क्या मैं सुन रहा हूँ, सोच रहा हूँ या बोल रहा हूँ।',
      'tutorial_camera_off_title': 'कैमरा बंद करें',
      'tutorial_camera_off_desc': 'अगर आपको कुछ दिखाना नहीं है, तो कैमरा बंद करके सिर्फ बात करें।',
      'tutorial_history_title': 'आपका इतिहास',
      'tutorial_history_desc': 'आप अपनी पिछली सभी बातचीत यहाँ देख सकते हैं।',
      'tutorial_language_title': 'भाषा बदलें',
      'tutorial_language_desc': 'अपनी भाषा बदलने के लिए यहाँ क्लिक करें।',
      'tutorial_swipe_next': 'अगला देखने के लिए स्वाइप करें।',
      'tutorial_swipe_finish': 'खत्म करने के लिए स्वाइप करें।',
    },
    Language.marathi: {
      'app_name': 'सहायक',
      'point_here': 'इथे दाखवा',
      'press_to_speak': 'बोलण्यासाठी खालचे बटण दाबा',
      'listening': 'ऐकत आहे...',
      'thinking': 'विचार करत आहे...',
      'speaking': 'बोलत आहे...',
      'error_occurred': 'काहीतरी चूक झाली. पुन्हा प्रयत्न करा.',
      'ask_question': 'काहीतरी प्रश्न विचारा',
      'welcome_message': 'नमस्ते. मी सहायक आहे. आपला प्रश्न विचारा किंवा काहीतरी दाखवा.',
      'change_language': 'भाषा बदला',
      'settings': 'सेटिंग्स',
      'text_size': 'अक्षरांचा आकार',
      'voice_speed': 'बोलण्याचा वेग',
      'normal': 'सामान्य',
      'large': 'मोठे',
      'extra_large': 'सर्वात मोठे',
      'slow': 'हळू',
      'fast': 'वेगात',
      'stop_speaking': 'बोलणे थांबवा',
      'flip_camera': 'कैमरा बदला',
      'choose_language': 'तुमची भाषा निवडा',
      'connection_error': 'क्षमस्व, आता कनेक्शन नाहीये. थोड्या वेळानी प्रयत्न करा.',
      'camera_error': 'कॅमेरा सुरू होऊ शकला नाही. ऐप पुन्हा उघडा.',
      'api_error': 'AI सेवेत काहीतरी चूक झाली. थोड्या वेळानी प्रयत्न करा.',
      'permission_error': 'कॅमेरा आणि माइकची परवानगी हवी.',
      'scan_barcode': 'बारकोड स्कॅन',
      'scanning': 'स्कॅन होत आहे...',
      'barcode_found': 'मला या उत्पादाचा बारकोड सापडला.',
      'history_count': 'तुमच्या {n} संभाषणे आहेत।',
      'history_play_prompt': 'ऐकण्यासाठी मधला बटण दाबा।',
      'history_you_asked': 'तुम्ही विचारले:',
      'history_i_said': 'मी म्हणालो:',
      'history_older': 'जुने संभाषण।',
      'history_newer': 'नवे संभाषण।',
      'history_oldest_reached': 'हे तुमचे सर्वात जुने संभाषण आहे।',
      'history_newest_reached': 'हे तुमचे सर्वात नवे संभाषण आहे।',
      'history_empty': 'अजून कोणतेही संभाषण नाही।',
      'tutorial_next': 'पुढे',
      'tutorial_finish': 'पूर्ण',
      'tutorial_skip': 'वगळा',
      'tutorial_welcome_title': 'सहायक मध्ये तुमचे स्वागत आहे!',
      'tutorial_welcome_desc': 'ॲप कसे वापरायचे ते पाहूया.',
      'tutorial_mic_title': 'माझ्याशी बोला',
      'tutorial_mic_desc': 'प्रश्न विचारण्यासाठी हे बटण दाबून ठेवा.',
      'tutorial_camera_title': 'कॅमेरा बदला',
      'tutorial_camera_desc': 'पुढचा आणि मागचा कॅमेरा बदलण्यासाठी याचा वापर करा.',
      'tutorial_flash_title': 'प्रकाश चालू करा',
      'tutorial_flash_desc': 'अंधार असल्यास, फ्लॅश चालू करण्यासाठी याचा वापर करा.',
      'tutorial_orb_title': 'स्थिती दिवा',
      'tutorial_orb_desc': 'मी ऐकत आहे, विचार करत आहे की बोलत आहे हे हा दिवा दाखवतो.',
      'tutorial_camera_off_title': 'कॅमेरा बंद करा',
      'tutorial_camera_off_desc': 'काही दाखवायचे नसल्यास, कॅमेरा बंद करून फक्त बोला.',
      'tutorial_history_title': 'तुमचा इतिहास',
      'tutorial_history_desc': 'तुम्ही तुमच्या सर्व मागील संभाषणांचा तपशील इथे पाहू शकता.',
      'tutorial_language_title': 'भाषा बदला',
      'tutorial_language_desc': 'तुमची भाषा बदलण्यासाठी इथे क्लिक करा.',
      'tutorial_swipe_next': 'पुढील पाहण्यासाठी स्वाइप करा.',
      'tutorial_swipe_finish': 'पूर्ण करण्यासाठी स्वाइप करा.',
    },
    Language.telugu: {
      'app_name': 'సహాయక్',
      'point_here': 'ఇక్కడ చూపించండి',
      'press_to_speak': 'మాట్లాడటానికి క్రింది బటన్‌ను నొక్కండి',
      'listening': 'వింటున్నాను...',
      'thinking': 'ఆలోచిస్తున్నాను...',
      'speaking': 'మాట్లాడుతున్నాను...',
      'error_occurred': 'ఏదో తప్పు జరిగింది. మళ్ళీ ప్రయత్నించండి.',
      'ask_question': 'ఏదైనా ప్రశ్న అడగండి',
      'welcome_message': 'నమస్తే. నేను సహాయక్. మీ ప్రశ్న అడగండి లేదా ఏదైనా చూపించండి.',
      'change_language': 'భాష మార్చండి',
      'settings': 'సెట్టింగులు',
      'text_size': 'అక్షర పరిమాణం',
      'voice_speed': 'మాట్లాడే వేగం',
      'normal': 'సామాన్యం',
      'large': 'పెద్దది',
      'extra_large': 'చాలా పెద్దది',
      'slow': 'మెల్లగా',
      'fast': 'వేగంగా',
      'stop_speaking': 'మాట్లాడటం ఆపండి',
      'flip_camera': 'కెమెరా మార్చండి',
      'choose_language': 'మీ భాషను ఎంచుకోండి',
      'connection_error': 'క్షమించండి, ఇప్పుడు కనెక్షన్ లేదు. కొంత సేపు అయ్యాక ప్రయత్నించండి.',
      'permission_error': 'మైక్ మరియు కెమెరా అనుమతి కావాలి. సెట్టింగ్స్ లోకి వెళ్లి ఆన్ చేయండి.',
      'camera_error': 'కెమెరా మొదలు కాలేదు. యాప్ మళ్ళీ ఓపెన్ చేయండి.',
      'api_error': 'AI సర్వీస్ లో ఏదో తప్పు జరిగింది. కొంత సేపు అయ్యాక ప్రయత్నించండి.',
      'scan_barcode': 'బార్‌కోడ్ స్కాన్',
      'scanning': 'స్కాన్ అవుతోంది...',
      'barcode_found': 'నాకు ఈ ఉత్పత్తి యొక్క బార్‌కోడ్ కనిపించింది.',
      'history_count': 'మీకు {n} సంభాషణలు ఉన్నాయి.',
      'history_play_prompt': 'వినడానికి మధ్య బటన్ నొక్కండి.',
      'history_you_asked': 'మీరు అడిగారు:',
      'history_i_said': 'నేను చెప్పాను:',
      'history_older': 'పాత సంభాషణ.',
      'history_newer': 'కొత్త సంభాషణ.',
      'history_oldest_reached': 'ఇది మీ పాత సంభాషణ.',
      'history_newest_reached': 'ఇది మీ కొత్త సంభాషణ.',
      'history_empty': 'ఇంకా సంభాషణలు లేవు.',
      'tutorial_next': 'తర్వాత',
      'tutorial_finish': 'పూర్తి',
      'tutorial_skip': 'దాటవేయి',
      'tutorial_welcome_title': 'సహాయక్ కు స్వాగతం!',
      'tutorial_welcome_desc': 'యాప్‌ను ఎలా ఉపయోగించాలో చూద్దాం.',
      'tutorial_mic_title': 'నాతో మాట్లాడండి',
      'tutorial_mic_desc': 'ప్రశ్న అడగడానికి ఈ బటన్‌ను నొక్కి పట్టుకోండి.',
      'tutorial_camera_title': 'కెమెరా మార్చండి',
      'tutorial_camera_desc': 'ఫ్రంట్ మరియు బ్యాక్ కెమెరా మధ్య మారడానికి దీన్ని ఉపయోగించండి.',
      'tutorial_flash_title': 'లైట్ ఆన్ చేయండి',
      'tutorial_flash_desc': 'చీకటిగా ఉంటే, ఫ్లాష్ ఆన్ చేయడానికి దీన్ని ఉపయోగించండి.',
      'tutorial_orb_title': 'స్థితి లైట్',
      'tutorial_orb_desc': 'నేను వింటున్నానా, ఆలోచిస్తున్నానా లేదా మాట్లాడుతున్నానా అనేది ఇది చూపిస్తుంది.',
      'tutorial_camera_off_title': 'కెమెరా ఆపండి',
      'tutorial_camera_off_desc': 'చూపించాల్సింది ఏమీ లేకపోతే, కెమెరా ఆపి కేవలం మాట్లాడండి.',
      'tutorial_history_title': 'మీ చరిత్ర',
      'tutorial_history_desc': 'మీరు మీ మునుపటి సంభాషణలన్నింటినీ ఇక్కడ కనుగొనవచ్చు.',
      'tutorial_language_title': 'భాష మార్చండి',
      'tutorial_language_desc': 'మీ భాషను మార్చడానికి ఇక్కడ క్లిక్ చేయండి.',
      'tutorial_swipe_next': 'తదుపరిది చూడటానికి స్వైప్ చేయండి.',
      'tutorial_swipe_finish': 'పూర్తి చేయడానికి స్వైప్ చేయండి.',
    },
    Language.english: {
      'app_name': 'Sahayak',
      'point_here': 'Point here',
      'press_to_speak': 'Press the button below to speak',
      'listening': 'Listening...',
      'thinking': 'Thinking...',
      'speaking': 'Speaking...',
      'error_occurred': 'Something went wrong. Try again.',
      'ask_question': 'Ask a question',
      'welcome_message': 'Hello. I am Sahayak. Ask your question or show me something.',
      'change_language': 'Change language',
      'settings': 'Settings',
      'text_size': 'Text size',
      'voice_speed': 'Voice speed',
      'normal': 'Normal',
      'large': 'Large',
      'extra_large': 'Extra Large',
      'slow': 'Slow',
      'fast': 'Fast',
      'stop_speaking': 'Stop speaking',
      'flip_camera': 'Flip camera',
      'choose_language': 'Choose your language',
      'connection_error': 'Sorry, no connection right now. Please try again in a moment.',
      'camera_error': 'Camera could not start. Please restart the app.',
      'api_error': 'AI service error. Please try again in a moment.',
      'permission_error': 'Camera and mic permissions are required.',
      'scan_barcode': 'Barcode Scan',
      'scanning': 'Scanning...',
      'barcode_found': 'I found a barcode on this product.',
      'history_count': 'You have {n} conversations.',
      'history_play_prompt': 'Press the middle button to listen.',
      'history_you_asked': 'You asked:',
      'history_i_said': 'I said:',
      'history_older': 'Older conversation.',
      'history_newer': 'Newer conversation.',
      'history_oldest_reached': 'This is your oldest conversation.',
      'history_newest_reached': 'This is your newest conversation.',
      'history_empty': 'No conversations yet.',
      'tutorial_next': 'Next',
      'tutorial_finish': 'Finish',
      'tutorial_skip': 'Skip',
      'tutorial_welcome_title': 'Welcome to Sahayak!',
      'tutorial_welcome_desc': "Let's take a quick tour of how to use the app.",
      'tutorial_mic_title': 'Talk to me',
      'tutorial_mic_desc': 'Press and hold this button to ask a question.',
      'tutorial_camera_title': 'Change View',
      'tutorial_camera_desc': 'Use this to switch between front and back cameras.',
      'tutorial_flash_title': 'Turn on Light',
      'tutorial_flash_desc': "If it's dark, use this to turn on the flash.",
      'tutorial_orb_title': 'Status Light',
      'tutorial_orb_desc': 'This shows if I am listening, thinking, or speaking.',
      'tutorial_camera_off_title': 'Turn Camera Off',
      'tutorial_camera_off_desc': 'If you have nothing to show, turn the camera off and just talk.',
      'tutorial_history_title': 'Your History',
      'tutorial_history_desc': 'You can find all your previous conversations here.',
      'tutorial_language_title': 'Change Language',
      'tutorial_language_desc': 'Click here to change your language at any time.',
      'tutorial_swipe_next': 'Swipe to see the next step.',
      'tutorial_swipe_finish': 'Swipe to finish the tutorial.',
    },
  };

  String translate(String key) {
    return _localizedValues[language]?[key] ?? key;
  }
}